version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: investigitor
      POSTGRES_USER: ninja
      POSTGRES_PASSWORD: pass
  gittorrentmock:
    image: nginx
    ports:
      - "3001:80"
    volumes:
      - ./dump:/usr/share/nginx/html
