version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /mnt/data/investigitor:/investigitor
      - /mnt/data/data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: investigitor
      POSTGRES_USER: ninja
      POSTGRES_PASSWORD: pass
  investigitor:
    build: ./investigitor
    depends_on:
      - db
    links:
      - db
    volumes:
      - /mnt/data/investigitor:/investigitor
    environment:
      GHTORRENT_URL: http://ghtorrent-downloads.ewi.tudelft.nl/mysql/mysql-2018-03-01.tar.gz
      GHTORRENT_FOLDER: /investigitor/mysql-2018-03-01/
      GHTORRENT_FILE: /investigitor/latest.tar.gz
      CLONE_FOLDER: /investigitor/repos/
      DB_HOST: db